### ISSUE TITLE
Lambda values computation

### ISSUE THREAD

**Issue by michele-milesi** [kc-ml2/SimpleDreamer#6]
https://github.com/kc-ml2/SimpleDreamer/blob/6ebf6405b87c9f1e187250ad7e2ffc701b99c74d/dreamer/utils/utils.py#L71

I would like to ask for an explanation of how you calculate lambda values. I do not understand why you remove the first reward and the first done.

Thank you in advance.

**Comment by seolhokim** [comment]
Thank you for bringing up the lambda value calculation in our implementation. Your question prompted me to take a closer look, and I realized that our compute_lambda_values function was incorrectly modified during a recent refactoring.

To clarify, removing the last reward and last continue flags from the input rewards and continue flags is not correct. Instead, we should only remove the first reward and continue flags.

It will be updated after some experiments. If you have any further questions or concerns, please feel free to let us know.
