### ISSUE TITLE
Tanh function applied to the output of representation and transition models

### ISSUE THREAD

**Issue by michele-milesi** [kc-ml2/SimpleDreamer#8]
`RepresentationModel`
https://github.com/kc-ml2/SimpleDreamer/blob/e12d4dbdd7206db5b52250679c6efb0fd1263cfa/dreamer/modules/model.py#L93

`TransitionModel`
https://github.com/kc-ml2/SimpleDreamer/blob/e12d4dbdd7206db5b52250679c6efb0fd1263cfa/dreamer/modules/model.py#L67

`create_normal_dist`
https://github.com/kc-ml2/SimpleDreamer/blob/e12d4dbdd7206db5b52250679c6efb0fd1263cfa/dreamer/utils/utils.py#L59

Hi, I have another question about your implementation: why do you apply the tanh function to the output of the representation and transition models?
In the `forward` methods of both representation and transition model you do not pass the std as actual parameter, so the tanh function is applied to the chunked input `x`.

In the paper I have not read about any application of the tanh function to the output of the representation and transition models, so I would like to ask you if you have observed some improvements with this choice or if you have used it for other reasons.

I thank you in advance for your helpfulness.

**Comment by seolhokim** [comment]
Thank you for your ongoing interest. We've considered that scaling the output could be beneficial, but we haven't tested it yet. I believe it would be worthwhile to specify it.
